### ISSUE TITLE
panning only works in two axes

### ISSUE THREAD

**Issue by MannyMeadows** [tizzle/aframe-orbit-controls-component#15]
Panning in the z-axis seems to have broken. Panning horizontally will only work in the x-axis.

Thanks for your efforts.

**Comment by tizzle** [comment]
Hey @MannyMeadows,

i made a short video while trying to figure out how to fix this. You can see it here:
http://eightdaysaweek.cc/files/AOC_PANNING.mp4

Panning can be achieved by pressing ctrl or by using three fingers on a touch device.
Is this not the intended panning behaviour? What did you expect?

Thanks and Cheers,

Till

**Comment by MannyMeadows** [comment]
Thanks for your reply.

I'm afraid your video only demonstrates the X & Y axes. If you rotate the scene by 90 degrees and try panning along the Z axis, you'll find that it is restricted to one horizontal axis only - panning along the Z axis will result in a zooming behaviour.

All axes were panning fine before the last update.

**Comment by tizzle** [comment]
Ok, i think i understand now.

With the last update there was some serious rewrite of the internal behaviour. This should have rather been a new feature-version instead of just a patch-version. I guess i got to learn that, i'm quite in experienced with maintaining a public project so far :)

Thanks for your explanation. I will look into this!

**Comment by tizzle** [comment]
Hey @MannyMeadows,

i just pushed a new version that should fix this. Please check!

Cheers

Till

**Comment by MannyMeadows** [comment]
Perfect. Thanks for adressing this so quickly.

Keep up the good work. 

Mark
