### ISSUE TITLE
Can't rotate when obj model is rendered in wireframe

### ISSUE THREAD

**Issue by Mostafa3la2** [tizzle/aframe-orbit-controls-component#34]
The component doesn't seem to work when I have an obj model with default material and wireframe mode set to true, the console logs this error message : "TypeError: o.position is undefined"

**Comment by tizzle** [comment]
Hey @Mostafa3la2,

is it possible you share your project or a reduced use-case?

Thanks a lot!

Cheers

Till

**Comment by Mostafa3la2** [comment]
Here you are, I also tried different models, same result.

[orbit-controls.zip](https://github.com/tizzle/aframe-orbit-controls-component/files/1692935/orbit-controls.zip)

**Comment by tizzle** [comment]
I'm not sure this is an issue related to the Orbit Controls. When removing the controls from your project, the issue remains.

I think the problem lies in combining the OBJ and the wireframe material. The error log implies this:
```
three.js:17006 Uncaught TypeError: Cannot read property 'array' of undefined
    at Object.o [as getWireframeAttribute] (three.js:17006)
    at we.renderBufferDirect (three.js:21570)
    at y (three.js:22272)
    at v (three.js:22245)
    at we.render (three.js:22009)
    at THREE.VREffect.render (VREffect.js:413)
    at HTMLElement.value (a-scene.js:637)
    at HTMLElement.render (bind.js:12)
    at e (a-scene.js:526)
    at HTMLElement.<anonymous> (a-scene.js:510)
```
When setting `wirframe:true` to `wireframe: false` the Orbit Controls work. I think the aforementioned error simply stops orbit controls from executing. I did a quick Google search on the error, but nothing meaningful came up. I'd recommend you looking into Aframe/ThreeJS problems with rendering obj together with a wireframe model.
Let me know how it goes!

Cheers

**Comment by Mostafa3la2** [comment]
Oh, my bad, should've tried this first, anyway thanks for your help and for this amazing script .
