### ISSUE TITLE
minPolarAngle/maxPolarAngle Infinity possible?

### ISSUE THREAD

**Issue by dirkk0** [tizzle/aframe-orbit-controls-component#38]
First of all: thanks for this plugin!

Then: I try to disable the Azimuth lock, to be able to freely rotate an object. I expected this to work, but it didn't:

              minPolarAngle: -Infinity;
              maxPolarAngle: Infinity;

Any ideas?

**Comment by tizzle** [comment]
Hey @dirkk0,

if i understand you correctly then what you are trying to achieve is not possible with Orbit Controls. This component takes a camera and moves it on a sphere around the target. The target object itself is not manipulated in any way. Due to the nature of the camera movement it will always feel different from freely rotating an object. 

If you want object rotation with inertia, i fear you have to search elsewhere or roll your own solution.

Maybe i dod not fully grasp what you're trying to achieve. If so, then please provide some more information what behaviour you expect. 

Apart from that, i recommend you use [this Orbit Controls lib](https://github.com/ngokevin/kframe/tree/master/components/orbit-controls) instead, as it is far more performant.

**Comment by dirkk0** [comment]
yes, you understood correctly - thanks for clarifying this!
This was not a hard requirement, so it doesn't matter too much for my particular project.
I look into Kevins Controls also, thanks for pointing this out.

Closing this.
