### ISSUE TITLE
camera FOV

### ISSUE THREAD

**Issue by jaap3d** [tizzle/aframe-orbit-controls-component#9]
Hi. Two possibly related questions.

1. How can I set a camera FOV when using orbit-controls-component?
2. What is minZoom and maxZoom for? The term _zoom_ is used in enableZoom and zoomSpeed, but I can't get minZoom and maxZoom to do anything, since mouse-scroll is actually dolly-ing the camera. In the code, it seems all zoom-related actions (by mouse and by touch) are handled via dolly-ing. The limits minDistance and maxDistance are working fine here, but I need actual zoom.

Am I missing something? Thanks.

**Comment by tizzle** [comment]
Hey @jaap3d,

i have to issue a small disclaimer before trying to answer your questions. I'm not a classic programmer, but a designer that practices programming to build prototypes. I ported this component from the threeJS because i needed it in a project. This was – due to my limited experience – mostly copy pasting and tweaking stuff until it worked. I then put it on github because i thought why not and now i'm here. Anyways, it is great to see people actually using it and wanting it to improve. I will try my best to do so.

Trying to answer your questions:
1. It's not possible until now but i will look into it and add it as a feature request, ok?
2. I don't think you're missing something. I will look in this.

**Comment by tizzle** [comment]
Hey @jaap3d,

i took the time to look through the whole source code and compare it with the [original OrbitControls](https://github.com/mattdesl/three-orbit-controls/blob/master/index.js). It turns out the zoom is just for orthographic cameras that cannot dolly like a perspective camera can. I will update the README to reflect this restriction.

Can you maybe explain your use case for the zoom? I currently can't see that you can't achieve the same effect with the position/dolly.

Thanks a lot and cheers,

Till

**Comment by tizzle** [comment]
Hey @jaap3d,

i just found that POV and zoom can be set on the camera entity. Please have a look at the basic example of v0.1.3.

Thanks!

**Comment by jaap3d** [comment]
Hi @tizzle,

Thanks a lot for looking into this. I'm a designer (just like you) and really not a programmer. My issue with zoom instead of dolly was because I'm working on a project with a small object: interacting with a phone. When close to the object, with dolly, the perspective angles get exaggerated when rotating the thing. If you keep a bit of distance and actually zoom in, the object stays nicely in proportion. Also, you see much less of the background whooshing by.
You mentioned v0.1.3. This was the master branch? Is it now changed to v0.1.4. Are older versions still accessible? I have a problem with your examples. They reference `<script src="../build.js"></script>` and when I run the master-branch locally, I don't have this `build.js`. Again: am I missing something? :)
Cheers.

**Comment by tizzle** [comment]
Hey @jaap3d,

i feel i forgot something, as i always use the npm packages. I will have a look.

Cheers

Till

**Comment by tizzle** [comment]
Hey @jaap3d,

the build.js was not added to the repository and only available once you built it locally. I now updated the repository to also include this. The examples now should work out of the box, i also added a link to examples in the README. 

Once you cloned this repository (newest version v0.1.5) you should be able to run the examples by simply opening the index.html in the examples folder.

Let me know how it goes!

Cheers

**Comment by jaap3d** [comment]
Hi.

Awesome work! The examples are great. Thanks for fixing the FOV issue.

Next, I'll be developing my mouse-interface (using your orbit-cam). In the past couple days, I've worked on the look-only interface for HMD's. I think it's very awkward and not really usable. If you like, take a look at my project over at [jaapdankert.nl/iphone](http://jaapdankert.nl/iphone) and tell me what you think (you're supposed to find 2 screws on the bottom and then pop the front off). It's going to be a demo of web-based technical training.

Cheers, Jaap.
